server:
  port: 8771
  
spring:
  profiles:
    active: pro
  application:
    name: gen-auth
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: CTT
    default-property-inclusion: non_null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis-plus:
  mapperLocations: "classpath*:mapper/*.xml"
