spring:
  datasource:
    name: test
    url: jdbc:mysql://10.10.10.182:3306/ag_auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: wshun
    password: 2019

eureka:
  instance:
    version: 1.0
    hostname: 127.0.0.1
    instanceId: 1000100122000001
    metadataMap:
      zone: 1001
    appGroupName: auth
  client:
    zone: 1001
    serviceUrl:
      defaultZone: http://wshunvx:QRVF68VKEV3B830V@127.0.0.1:8761/eureka/
    preferSameZoneEureka: true
